version: "3.1"

services:
  web:
    build: .
    container_name: web
    restart: always
    environment:
      - MONGODB_URI=mongodb://root:password@mongodb:27017/test
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - backend

networks:
  backend:
