version: "3"
services:
  mongodb-primary:
    image: docker.io/bitnami/mongodb:6.0
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    volumes:
      - "mongodb_master_data:/bitnami/mongodb"

  mongodb-secondary:
    image: docker.io/bitnami/mongodb:6.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123

  mongodb-arbiter:
    image: docker.io/bitnami/mongodb:6.0
    depends_on:
      - mongodb-primary
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
  redis:
    container_name: redis_container
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data/redis
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - NODE_ENV=development
      # - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_URI=mongodb://root:password123@mongodb-primary:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
      - redis
volumes:
  mongodb_master_data:
    driver: local
  redis: {}
