version: "3"
services:
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT: 5000
      - MONGODB_URI: mongodb://mongodb:27017
    depends_on:
      - mongodb
volumes:
  mongodb: {}
