version: "3.1"

services:
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb+srv://cloudrid:LVhjqSpCO6LYQbyk@cluster.c7trxkr.mongodb.net/cloudrid?retryWrites=true&w=majority
    networks:
      - backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_URI=mongodb://root:example@mongodb:27017/test
    volumes:
      - ./data:/data/db
    networks:
      - backend

networks:
  backend:
