version: "3"
services:
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  redis-primary:
    image: docker.io/bitnami/redis:7.0
    ports:
      - "6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - "redis_data:/bitnami/redis/data"

  redis-secondary:
    image: docker.io/bitnami/redis:7.0
    ports:
      - "6379"
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_password
      - REDIS_PASSWORD=my_password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis-primary
      - redis-secondary
volumes:
  mongodb: {}
  redis_data: { driver: local }
