version: "3"
services:
  mongodb:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  redis:
    container_name: redis_container
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data/redis
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_URI=redis://my_password@redis-primary:6379
    depends_on:
      - mongodb
      - redis-primary
      - redis-secondary
volumes:
  mongodb: {}
  redis: {}
